export const USUARIO_LOGIN = "USUARIO_LOGIN";

export const ELEGIR_DASHBOARD = "ELEGIR_DASHBOARD";

export const ASIGNAR_PROYECTO = "ASIGNAR_PROYECTO";

export const CREAR_TAREA = "CREAR_TAREA";
export const CREAR_PROYECTO = "CREAR_PROYECTO";

export const SELECCIONAR_PROYECTO_INFO = "SELECCIONAR_PROYECTO_INFO";
